export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS app_users (
    id TEXT PRIMARY KEY,
    email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS children (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    image_data BYTEA NOT NULL,
    image_mime TEXT NOT NULL,
    face_descriptor DOUBLE PRECISION[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS children_user_id_created_at_idx
    ON children (user_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS photo_sessions (
    id BIGSERIAL PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    goals JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS photo_sessions_user_id_updated_at_idx
    ON photo_sessions (user_id, updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS photos (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES photo_sessions(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    image_data BYTEA NOT NULL,
    image_mime TEXT NOT NULL,
    quality TEXT NOT NULL DEFAULT 'good',
    quality_reasons JSONB NOT NULL DEFAULT '[]'::jsonb,
    quality_score INTEGER,
    shot_type TEXT NOT NULL DEFAULT 'individual',
    child_id BIGINT REFERENCES children(id) ON DELETE SET NULL,
    matched_child_ids BIGINT[] NOT NULL DEFAULT '{}',
    activity TEXT,
    selected BOOLEAN NOT NULL DEFAULT TRUE,
    best_key TEXT,
    is_best BOOLEAN NOT NULL DEFAULT FALSE,
    duplicate_of BIGINT REFERENCES photos(id) ON DELETE SET NULL,
    is_duplicate BOOLEAN NOT NULL DEFAULT FALSE,
    perceptual_hash TEXT,
    activity_confidence DOUBLE PRECISION,
    activity_reason TEXT,
    activity_source TEXT NOT NULL DEFAULT 'filename',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE INDEX IF NOT EXISTS photos_session_id_created_at_idx
    ON photos (session_id, created_at, id)`,
  `ALTER TABLE photo_sessions ADD COLUMN IF NOT EXISTS goals JSONB NOT NULL DEFAULT '{}'::jsonb`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS quality TEXT NOT NULL DEFAULT 'good'`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS quality_reasons JSONB NOT NULL DEFAULT '[]'::jsonb`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS quality_score INTEGER`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS shot_type TEXT NOT NULL DEFAULT 'individual'`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS child_id BIGINT REFERENCES children(id) ON DELETE SET NULL`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS matched_child_ids BIGINT[] NOT NULL DEFAULT '{}'`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS activity TEXT`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS selected BOOLEAN NOT NULL DEFAULT TRUE`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS best_key TEXT`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS is_best BOOLEAN NOT NULL DEFAULT FALSE`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS duplicate_of BIGINT REFERENCES photos(id) ON DELETE SET NULL`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN NOT NULL DEFAULT FALSE`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS perceptual_hash TEXT`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS activity_confidence DOUBLE PRECISION`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS activity_reason TEXT`,
  `ALTER TABLE photos ADD COLUMN IF NOT EXISTS activity_source TEXT NOT NULL DEFAULT 'filename'`,
] as const;
